//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVSeoSdkDotNet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BVSeoSdkDotNet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error please verify the exception stack trace for further info.;.
        /// </summary>
        internal static string ERR0000 {
            get {
                return ResourceManager.GetString("ERR0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code is null please set proper error code.;.
        /// </summary>
        internal static string ERR0001 {
            get {
                return ResourceManager.GetString("ERR0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error retrieving the property or the property is not set properly.;.
        /// </summary>
        internal static string ERR0002 {
            get {
                return ResourceManager.GetString("ERR0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The getAggregateRating method is only supported when schema.org is configured for structured markup.  Please submit a support ticket at spark.bazaarvoice.com to have your Bazaarvoice configuration updated to use schema.org for structured markup.;.
        /// </summary>
        internal static string ERR0003 {
            get {
                return ResourceManager.GetString("ERR0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error loading bvconfig properties please check the exception.;.
        /// </summary>
        internal static string ERR0004 {
            get {
                return ResourceManager.GetString("ERR0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error loading bvclient properties please check the exception.;.
        /// </summary>
        internal static string ERR0005 {
            get {
                return ResourceManager.GetString("ERR0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add empty or null values to configuration.;.
        /// </summary>
        internal static string ERR0006 {
            get {
                return ResourceManager.GetString("ERR0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BVConfiguration is null, please set a valid BVConfiguration.;.
        /// </summary>
        internal static string ERR0007 {
            get {
                return ResourceManager.GetString("ERR0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property for Bazaarvoice server configuration is not configured properly.;.
        /// </summary>
        internal static string ERR0008 {
            get {
                return ResourceManager.GetString("ERR0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property for Bazaarvoice client configuration is not configured properly.;.
        /// </summary>
        internal static string ERR0009 {
            get {
                return ResourceManager.GetString("ERR0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCAL_SEO_FILE_ROOT is not configured in BVConfiguration.;.
        /// </summary>
        internal static string ERR0010 {
            get {
                return ResourceManager.GetString("ERR0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BVParameters is null.;.
        /// </summary>
        internal static string ERR0011 {
            get {
                return ResourceManager.GetString("ERR0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource to the URL or file is currently unavailable.;.
        /// </summary>
        internal static string ERR0012 {
            get {
                return ResourceManager.GetString("ERR0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The getReviews method is only supported when schema.org is configured for structured markup.  Please submit a support ticket at spark.bazaarvoice.com to have your Bazaarvoice configuration updated  to use schema.org for structured markup.;.
        /// </summary>
        internal static string ERR0013 {
            get {
                return ResourceManager.GetString("ERR0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubjectId cannot be null or empty.;.
        /// </summary>
        internal static string ERR0014 {
            get {
                return ResourceManager.GetString("ERR0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contentType is null in BVParameters.;.
        /// </summary>
        internal static string ERR0015 {
            get {
                return ResourceManager.GetString("ERR0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subjectType is null in BVParameters.;.
        /// </summary>
        internal static string ERR0016 {
            get {
                return ResourceManager.GetString("ERR0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to userAgent in BVParameters is null.;.
        /// </summary>
        internal static string ERR0017 {
            get {
                return ResourceManager.GetString("ERR0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution timed out, exceeded {0}ms;.
        /// </summary>
        internal static string ERR0018 {
            get {
                return ResourceManager.GetString("ERR0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to reach the host please check your network.;.
        /// </summary>
        internal static string ERR0019 {
            get {
                return ResourceManager.GetString("ERR0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOUD_KEY is not configured in BVConfiguration..
        /// </summary>
        internal static string ERR0020 {
            get {
                return ResourceManager.GetString("ERR0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BV_ROOT_FOLDER is not configured in BVConfiguration..
        /// </summary>
        internal static string ERR0021 {
            get {
                return ResourceManager.GetString("ERR0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration error - pageURI contains invalid characters, correct or encode URI..
        /// </summary>
        internal static string ERR0022 {
            get {
                return ResourceManager.GetString("ERR0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration error - baseURI contains invalid characters, correct or encode URI..
        /// </summary>
        internal static string ERR0023 {
            get {
                return ResourceManager.GetString("ERR0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charset is not configured properly. BV-SEO-SDK will load default charset and continue.;.
        /// </summary>
        internal static string ERR0024 {
            get {
                return ResourceManager.GetString("ERR0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BV content validation failed. Verify firewall and cache response.;.
        /// </summary>
        internal static string ERR0025 {
            get {
                return ResourceManager.GetString("ERR0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution timed out for search bot, exceeded {0}ms;.
        /// </summary>
        internal static string ERR0026 {
            get {
                return ResourceManager.GetString("ERR0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URI - PageURI or BaseURI contains invalid characters, correct or encode URI..
        /// </summary>
        internal static string ERR0027 {
            get {
                return ResourceManager.GetString("ERR0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;ul id=&quot;BVSEOSDK_meta&quot; style=&quot;display:none!important;&quot;&gt;
        ///	&lt;li data-bvseo=&quot;sdk&quot;&gt;bvseo_sdk, net_sdk, ${version}&lt;/li&gt;
        ///	&lt;li data-bvseo=&quot;sp_mt&quot;&gt;${methodType}, ${accessMethod}, ${executionTime}ms&lt;/li&gt;
        ///	&lt;li data-bvseo=&quot;ct_st&quot;&gt;${_bvParameters.ContentType.uriValue().ToUpper()}, ${_bvParameters.SubjectType.uriValue().ToUpper()}&lt;/li&gt;
        ///#if (${message}) 
        ///	&lt;li data-bvseo=&quot;ms&quot;&gt;bvseo-msg: ${message}&lt;/li&gt;
        ///#end
        ///&lt;/ul&gt;
        ///
        ///#if (${revealMap})
        ///&lt;ul id=&quot;BVSEOSDK_DEBUG&quot; style=&quot;display:none;&quot;&gt;
        ///#foreach ($config in $revealMap [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string footer {
            get {
                return ResourceManager.GetString("footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed loading bvconfig.properties..
        /// </summary>
        internal static string MSG0000 {
            get {
                return ResourceManager.GetString("MSG0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bvclient.properties file found and continuing to load configuration from the file..
        /// </summary>
        internal static string MSG0001 {
            get {
                return ResourceManager.GetString("MSG0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bvclient.properties file not found and hence will continue without loading the file..
        /// </summary>
        internal static string MSG0002 {
            get {
                return ResourceManager.GetString("MSG0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEO SDK is disabled. Enable by setting seo.sdk.enabled to true..
        /// </summary>
        internal static string MSG0003 {
            get {
                return ResourceManager.GetString("MSG0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTION_TIMEOUT is set to 0 ms; JavaScript-only Display..
        /// </summary>
        internal static string MSG0004 {
            get {
                return ResourceManager.GetString("MSG0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTION_TIMEOUT_BOT is less than the minimum value allowed. Minimum value of 100ms used.;.
        /// </summary>
        internal static string MSG0005 {
            get {
                return ResourceManager.GetString("MSG0005", resourceCulture);
            }
        }
    }
}
